version: '3.8'

services:
  # Frontend React App
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped 