# Railway configuration for Confessly Backend
# Deploy this as the backend service

[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 