# Railway configuration for Confessly (Full Stack)
# Deploy this as a single service with both frontend and backend

[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run deploy"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Ensure proper build order
[build.steps]
preBuild = "npm run install-all" 