# Railway configuration for Confessly Backend
# Deploy this as the backend service

[build]
builder = "dockerfile"
dockerfile = "server/Dockerfile.prod"
context = "server"

[deploy]
startCommand = "node index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 