# Railway configuration for Confessly (Full Stack)
# Deploy this as a single service with both frontend and backend

[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 